<?php

return [
    'regions' => [
        'Arusha' => ['Arusha City', 'Arusha District', 'Karatu', 'Longido', 'Meru', 'Monduli', 'Ngorongoro'],
        'Dar es Salaam' => ['Ilala', 'Kigamboni', 'Kinondoni', 'Temeke', 'Ubungo'],
        'Dodoma' => ['Bahi', 'Chamwino', 'Chemba', 'Dodoma City', 'Kondoa', 'Kongwa', 'Mpwapwa'],
        'Geita' => ['Bukombe', 'Chato', 'Geita', 'Mbogwe', 'Nyangwale'],
        'Iringa' => ['Iringa District', 'Iringa Municipal', 'Kilolo', 'Mafinga Town', 'Mufindi'],
        'Kagera' => ['Biharamulo', 'Bukoba District', 'Bukoba Municipal', 'Karagwe', 'Kyerwa', 'Missenyi', 'Muleba', 'Ngara'],
        'Katavi' => ['Mlele', 'Mpanda District', 'Mpanda Municipal', 'Tanganyika'],
        'Kigoma' => ['Buhigwe', 'Kakonko', 'Kasulu District', 'Kasulu Town', 'Kibondo', 'Kigoma District', 'Kigoma-Ujiji Municipal', 'Uvinza'],
        'Kilimanjaro' => ['Hai', 'Moshi District', 'Moshi Municipal', 'Mwanga', 'Rombo', 'Same', 'Siha'],
        'Lindi' => ['Kilwa', 'Lindi District', 'Lindi Municipal', 'Liwale', 'Nachingwea', 'Ruangwa'],
        'Manyara' => ['Babati District', 'Babati Town', 'Hanang', 'Kiteto', 'Mbulu', 'Simanjiro'],
        'Mara' => ['Bunda', 'Butiama', 'Musoma District', 'Musoma Municipal', 'Rorya', 'Serengeti', 'Tarime'],
        'Mbeya' => ['Busokelo', 'Chunya', 'Kyela', 'Mbarali', 'Mbeya City', 'Mbeya District', 'Rungwe'],
        'Morogoro' => ['Gairo', 'Kilombero', 'Kilosa', 'Malinyi', 'Morogoro District', 'Morogoro Municipal', 'Mvomero', 'Ulanga'],
        'Mtwara' => ['Masasi District', 'Masasi Town', 'Mtwara District', 'Mtwara Municipal', 'Nanyumbu', 'Newala', 'Tandahimba'],
        'Mwanza' => ['Ilemela', 'Kwimba', 'Magu', 'Misungwi', 'Nyamagana', 'Sengerema', 'Ukerewe'],
        'Njombe' => ['Ludewa', 'Makambako Town', 'Makete', 'Njombe District', 'Njombe Town', 'Wangingombe'],
        'Pemba North' => ['Micheweni', 'Wete'],
        'Pemba South' => ['Chake Chake', 'Mkoani'],
        'Pwani' => ['Bagamoyo', 'Kibaha District', 'Kibaha Town', 'Kisarawe', 'Mafia', 'Mkuranga', 'Rufiji'],
        'Rukwa' => ['Kalambo', 'Nkasi', 'Sumbawanga District', 'Sumbawanga Municipal'],
        'Ruvuma' => ['Mbinga', 'Namtumbo', 'Nyasa', 'Songea District', 'Songea Municipal', 'Tunduru'],
        'Shinyanga' => ['Kahama Town', 'Kishapu', 'Shinyanga District', 'Shinyanga Municipal'],
        'Simiyu' => ['Bariadi', 'Busega', 'Itilima', 'Maswa', 'Meatu'],
        'Singida' => ['Ikungi', 'Iramba', 'Manyoni', 'Mkalama', 'Singida District', 'Singida Municipal'],
        'Songwe' => ['Ileje', 'Mbozi', 'Momba', 'Songwe', 'Tunduma Town'],
        'Tabora' => ['Igunga', 'Kaliua', 'Nzega District', 'Nzega Town', 'Sikonge', 'Tabora Municipal', 'Urambo', 'Uyui'],
        'Tanga' => ['Handeni District', 'Handeni Town', 'Kilindi', 'Korogwe District', 'Korogwe Town', 'Lushoto', 'Muheza', 'Mkinga', 'Pangani', 'Tanga City'],
        'Unguja North' => ['Kaskazini A', 'Kaskazini B'],
        'Unguja South' => ['Kati', 'Kusini'],
        'Unguja Urban West' => ['Magharibi A', 'Magharibi B', 'Mjini'],
    ],
];
